# Generated by Django 5.1.7 on 2025-04-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visao_sistemica', models.IntegerField()),
                ('visao_analitica', models.IntegerField()),
                ('foco_planejamento', models.IntegerField()),
                ('orientacao_mudancas', models.IntegerField()),
                ('relacoes_colaboracao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente_comite', models.IntegerField()),
                ('membro_comite', models.IntegerField()),
                ('presidente_portifolio', models.IntegerField()),
                ('membro_portifolio', models.IntegerField()),
                ('divulgacao_midea', models.IntegerField()),
                ('formulacao_politicas', models.IntegerField()),
                ('palestrante_disciplina_pos', models.IntegerField()),
                ('parcerias_embrapa', models.IntegerField()),
                ('parcerias_intituicoes', models.IntegerField()),
                ('responsavel_laboratorio', models.IntegerField()),
                ('acoes_gerenciais_locais', models.IntegerField()),
                ('treinamentos_capacitacoes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacao_editor', models.IntegerField()),
                ('clareza_coesao', models.IntegerField()),
                ('gestor_contratos', models.BooleanField(max_length=10)),
                ('valor_gestor_contratos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lideranca_projeto', models.IntegerField()),
                ('responsavel_solucao_contribuicao', models.IntegerField()),
                ('responsavel_atividade', models.IntegerField()),
                ('participacao_qualificacao', models.BooleanField(default=False)),
                ('coordenacao_propostas_projetos', models.BooleanField(default=False)),
                ('membro_propostas_projetos', models.BooleanField(default=False)),
                ('recursos_financeiros_comprovados', models.BooleanField(default=False)),
                ('valor_recursos_financeiros_comprovados', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instrutor_eventos_tecnicos', models.IntegerField()),
                ('apresentacao_tecnologias_embrapa', models.IntegerField()),
                ('responsvel_capacitacao_ead', models.IntegerField()),
                ('revisor_capacitacao_ead', models.IntegerField()),
                ('membro_capacitacao_ead', models.IntegerField()),
                ('coordenador_novas_capacitacoes', models.IntegerField()),
                ('artigo_a1', models.IntegerField()),
                ('artigo_a2_a3_a4', models.IntegerField()),
                ('artigo_b1_b2', models.IntegerField()),
                ('artigo_b3_inferior', models.IntegerField()),
                ('producoes_tecnicas_embrapa', models.IntegerField()),
                ('elaboracao_cap_livros', models.IntegerField()),
                ('organizacao_edicao_livros', models.IntegerField()),
                ('artigos_resumos_eventos', models.IntegerField()),
            ],
        ),
    ]
