# Generated by Django 5.1.7 on 2025-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_formulario_a_visao_sistemica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario_c',
            name='recursos_financeiros_comprovados',
        ),
        migrations.RemoveField(
            model_name='formulario_c',
            name='valor_gestor_contratos',
        ),
        migrations.AlterField(
            model_name='formulario_a',
            name='foco_planejamento',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_a',
            name='orientacao_mudancas',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_a',
            name='relacoes_colaboracao',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_a',
            name='visao_analitica',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_a',
            name='visao_sistemica',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='acoes_gerenciais_locais',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='divulgacao_midea',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='formulacao_politicas',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='membro_comite',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='membro_portifolio',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='palestrante_disciplina_pos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='parcerias_embrapa',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='parcerias_intituicoes',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='presidente_comite',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='presidente_portifolio',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='responsavel_laboratorio',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_b',
            name='treinamentos_capacitacoes',
            field=models.IntegerField(choices=[(4, 'Duas ou mais capacitações e ou treinamentos realizados pelo pesquisador'), (3, 'Uma capacitação e ou treinamento realizada pelo pesquisador'), (0, 'Capacitação não realizada')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='apresentacao_tecnologias_embrapa',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='artigo_a1',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='artigo_a2_a3_a4',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='artigo_b1_b2',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='artigo_b3_inferior',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='artigos_resumos_eventos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='atuacao_editor',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='clareza_coesao',
            field=models.IntegerField(choices=[(4, '100%'), (3, 'Acima de 60%'), (2, 'Entre 40% e 59%'), (1, 'Abaixo de 40%'), (0, 'Nenhum')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='coordenador_novas_capacitacoes',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='elaboracao_cap_livros',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='gestor_contratos',
            field=models.IntegerField(choices=[(4, 'Acima de R$ 200 mil'), (3, 'Entre R$ 80 e R$ 200 mil'), (2, 'Até R$ 80 mil'), (1, 'Sem ônus'), (0, 'Sem contrato')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='instrutor_eventos_tecnicos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='lideranca_projeto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='membro_capacitacao_ead',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='organizacao_edicao_livros',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='producoes_tecnicas_embrapa',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='responsavel_atividade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='responsavel_solucao_contribuicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='responsvel_capacitacao_ead',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='revisor_capacitacao_ead',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='formulario_c',
            name='valor_recursos_financeiros_comprovados',
            field=models.IntegerField(choices=[(4, 'Acima de R$ 51 mil'), (3, 'Entre R$ 21 mil e R$ 50 mil'), (2, 'Entre R$ 11 mil e R$ 20 mil '), (1, 'Até R$ 10 mil'), (0, 'Sem captação')], default=0.0),
        ),
    ]
