# Generated by Django 5.1.7 on 2025-05-03 04:24

import avaliaquick.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='email',
            field=models.EmailField(default='teste@gmail.com', max_length=254),
        ),
        migrations.CreateModel(
            name='Pendentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('arquivos', models.FileField(upload_to=avaliaquick.models.caminho_arquivo)),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliaquick.pesquisador')),
            ],
        ),
    ]
