# Generated by Django 5.1.7 on 2025-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoanual',
            name='data_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoanual',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
