# Generated by Django 5.1.7 on 2025-05-03 21:32

import avaliaquick.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0002_pesquisador_email_pendentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendentes',
            name='arquivos',
            field=models.FileField(null=True, upload_to=avaliaquick.models.caminho_arquivo),
        ),
    ]
