# Generated by Django 5.1.7 on 2025-05-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0003_alter_pendentes_arquivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendentes',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('AND', 'Andamento'), ('FIN', 'Finalizado')], default='PEN', max_length=3),
        ),
    ]
