# Generated by Django 5.1.7 on 2025-05-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0004_pendentes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='pesquisador',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
