# Generated by Django 5.1.7 on 2025-05-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0005_alter_pesquisador_email_alter_pesquisador_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
