# Generated by Django 5.1.7 on 2025-05-04 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0006_alter_pesquisador_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('media_nota', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('qtd_avaliados', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ABE', 'Aberta'), ('FEC', 'Fechada')], default='ABE', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='pendentes',
            name='avaliacaoAnual',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='avaliaquick.avaliacaoanual'),
        ),
    ]
