# Generated by Django 5.1.7 on 2025-05-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0007_avaliacaoanual_pendentes_avaliacaoanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoanual',
            name='data_fim',
            field=models.DateField(null=True),
        ),
    ]
