# Generated by Django 5.1.7 on 2025-05-05 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0008_alter_avaliacaoanual_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendentes',
            name='nota',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
