# Generated by Django 5.1.7 on 2025-05-07 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0010_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
