# Generated by Django 5.1.7 on 2025-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliaquick', '0011_pesquisador_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
